# Generated by Django 6.0.7 on 2026-07-25 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0002_document_updated_at'),
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConceptRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_concept', models.CharField(max_length=255)),
                ('to_concept', models.CharField(max_length=255)),
                ('relationship', models.CharField(max_length=100)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships', to='docs.document')),
            ],
            options={
                'unique_together': {('document', 'from_concept', 'to_concept')},
            },
        ),
    ]
