# Generated by Django 6.0.7 on 2026-08-05 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_conceptrelationship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conceptrelationship',
            name='from_concept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing', to='questions.concept'),
        ),
        migrations.AlterField(
            model_name='conceptrelationship',
            name='to_concept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming', to='questions.concept'),
        ),
    ]
