services:

  db:
    image: pgvector/pgvector:pg16

    container_name: documind_postgres

    environment:
      POSTGRES_DB: documind
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data: