# Generated by Django 6.0.7 on 2026-07-18 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentchunk',
            old_name='embedding_id',
            new_name='embedding',
        ),
    ]
