# Generated by Django 6.0.7 on 2026-07-25 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0002_rename_embedding_id_documentchunk_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentchunk',
            name='page_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
